// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjwjCIifxGCxzuQvoqpzSt_5SpgRHDN9Y',
    appId: '1:261310312102:web:d56239ac8603c8db4cce67',
    messagingSenderId: '261310312102',
    projectId: 'english-80178',
    authDomain: 'english-80178.firebaseapp.com',
    storageBucket: 'english-80178.appspot.com',
    measurementId: 'G-0PP18FGDY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo-7Lav3NOFEL5e_8OcXNGkGbUs_9gMIc',
    appId: '1:261310312102:android:2748ec3558eaae5d4cce67',
    messagingSenderId: '261310312102',
    projectId: 'english-80178',
    storageBucket: 'english-80178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDPegb79E9voy3mxh2F2BZQFHaPnsgHvA',
    appId: '1:261310312102:ios:b3c5cd4ea625d8314cce67',
    messagingSenderId: '261310312102',
    projectId: 'english-80178',
    storageBucket: 'english-80178.appspot.com',
    iosBundleId: 'com.example.english',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDPegb79E9voy3mxh2F2BZQFHaPnsgHvA',
    appId: '1:261310312102:ios:c7c5c0a36577a91a4cce67',
    messagingSenderId: '261310312102',
    projectId: 'english-80178',
    storageBucket: 'english-80178.appspot.com',
    iosBundleId: 'com.example.english.RunnerTests',
  );
}
